const github = "https://github.com/minchycheng-s/uk-financial-complaints-intelligence";

const styles = `
:root{--ink:#17201d;--muted:#60706a;--paper:#f4f1e9;--card:#fffdf8;--green:#174b3c;--lime:#caef6c;--line:#d8d8cc;--orange:#f16d3a}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--paper);color:var(--ink);font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}a{color:inherit;text-decoration:none}.shell{width:min(1180px,calc(100% - 42px));margin:auto}
nav{height:82px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid var(--line)}.brand{font-size:24px;font-weight:900}.brand span{color:var(--orange)}.navlinks{display:flex;align-items:center;gap:28px;font-size:14px;font-weight:650}.button{display:inline-flex;align-items:center;gap:9px;background:var(--ink);color:white;border-radius:99px;padding:13px 19px}.button.light{background:var(--lime);color:var(--ink)}
.hero{padding:92px 0 70px}.eyebrow{text-transform:uppercase;letter-spacing:.16em;color:var(--green);font-size:12px;font-weight:800}.hero-grid{display:grid;grid-template-columns:1.4fr .6fr;gap:65px;align-items:end}.hero h1{font-family:Georgia,serif;font-size:clamp(50px,7vw,91px);font-weight:400;line-height:.94;letter-spacing:-.055em;margin:25px 0 30px}.hero h1 em{color:var(--green)}.intro{font-size:19px;line-height:1.65;color:var(--muted);max-width:670px}.hero-side{border-left:1px solid var(--line);padding-left:30px}.hero-side strong{font-family:Georgia,serif;font-size:50px;font-weight:400;display:block}.hero-side p{color:var(--muted);line-height:1.6}.actions{display:flex;gap:12px;margin-top:32px}
.metrics{background:var(--green);color:white}.metrics-grid{display:grid;grid-template-columns:repeat(4,1fr)}.metric{padding:38px 24px;border-right:1px solid #ffffff35}.metric:last-child{border:0}.metric strong{display:block;font-family:Georgia,serif;font-size:42px;color:var(--lime)}.metric span{font-size:13px;color:#dce8e2}
.section{padding:90px 0}.section-head{display:grid;grid-template-columns:.7fr 1.3fr;gap:45px;margin-bottom:50px}.kicker{text-transform:uppercase;letter-spacing:.13em;color:var(--orange);font-size:12px;font-weight:800}.section h2{font-family:Georgia,serif;font-size:clamp(39px,5vw,64px);font-weight:400;letter-spacing:-.04em;line-height:1;margin:0}.section-head p{font-size:18px;line-height:1.65;color:var(--muted);margin:4px 0}
.workflow{display:grid;grid-template-columns:repeat(5,1fr);border:1px solid var(--line);background:var(--card)}.step{padding:29px 23px;min-height:210px;border-right:1px solid var(--line)}.step:last-child{border:0}.step b{color:var(--orange);font-size:12px}.step h3{font-family:Georgia,serif;font-size:27px;margin:35px 0 12px}.step p{color:var(--muted);line-height:1.55;font-size:14px}
.findings{background:#e8e5dc}.finding-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.finding{background:var(--card);padding:34px;border-top:5px solid var(--green);min-height:250px}.finding strong{font-family:Georgia,serif;font-size:64px;color:var(--green)}.finding h3{font-size:18px}.finding p{color:var(--muted);line-height:1.65}
.dashboard{background:#13251f;color:white;border-radius:24px;padding:28px;box-shadow:0 25px 70px #1a2d2525}.dash-top{display:flex;justify-content:space-between;align-items:center;margin-bottom:26px}.lights{display:flex;gap:7px}.lights i{width:9px;height:9px;border-radius:50%;background:#88a59a}.dash-grid{display:grid;grid-template-columns:1.15fr .85fr;gap:18px}.panel{background:#1c352c;border:1px solid #ffffff18;border-radius:14px;padding:22px}.panel h4{margin:0 0 22px;color:#d9e5df}.bars{height:220px;display:flex;align-items:end;gap:12px}.bar{flex:1;background:var(--lime);border-radius:7px 7px 0 0;min-height:18px}.bar:nth-child(2n){background:#f2a96d}.signals{display:grid;gap:13px}.signal{display:grid;grid-template-columns:1fr auto;gap:10px;align-items:center}.track{height:9px;background:#ffffff18;border-radius:20px;overflow:hidden}.fill{height:100%;background:var(--lime)}.signal small{color:#cbd8d3}
.skills{display:flex;flex-wrap:wrap;gap:10px}.chip{border:1px solid var(--line);background:var(--card);border-radius:99px;padding:10px 15px;font-size:13px}.lesson-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin-top:38px}.lesson{padding:25px 0;border-top:1px solid var(--line)}.lesson b{color:var(--orange)}.lesson p{line-height:1.6;color:var(--muted)}
footer{background:var(--ink);color:white;padding:70px 0}.footer-grid{display:grid;grid-template-columns:1.4fr .6fr;gap:40px;align-items:end}footer h2{font-family:Georgia,serif;font-size:50px;font-weight:400;margin:0 0 17px}footer p{color:#b8c4bf;line-height:1.6}.foot-links{display:flex;justify-content:flex-end;gap:13px}
@media(max-width:850px){.navlinks a:not(.button){display:none}.hero-grid,.section-head,.dash-grid,.footer-grid{grid-template-columns:1fr}.hero-side{border-left:0;border-top:1px solid var(--line);padding:25px 0 0}.metrics-grid{grid-template-columns:1fr 1fr}.metric:nth-child(2){border-right:0}.workflow{grid-template-columns:1fr}.step{border-right:0;border-bottom:1px solid var(--line);min-height:0}.finding-grid,.lesson-grid{grid-template-columns:1fr}.foot-links{justify-content:flex-start}.hero{padding-top:65px}}@media(max-width:520px){.shell{width:min(100% - 26px,1180px)}.metrics-grid{grid-template-columns:1fr}.metric{border-right:0;border-bottom:1px solid #ffffff35}.actions{flex-direction:column;align-items:flex-start}}
`;

const html = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="A data analytics portfolio case study transforming FCA complaints workbooks into transparent, reviewable customer-harm intelligence."><title>UK Financial Complaints Intelligence</title><style>${styles}</style></head>
<body>
<nav class="shell"><a class="brand" href="#top">MC<span>.</span></a><div class="navlinks"><a href="#case">Case study</a><a href="#findings">Findings</a><a href="#method">Method</a><a class="button" href="${github}" target="_blank" rel="noreferrer">View GitHub ↗</a></div></nav>
<main>
<section class="hero shell" id="top"><div class="eyebrow">Data analytics portfolio · FCA complaints</div><div class="hero-grid"><div><h1>From difficult Excel files to <em>decision-ready intelligence.</em></h1><p class="intro">An end-to-end analytics project that profiles, extracts and validates UK firm-level complaints data—then turns it into explainable early-warning signals and Tableau dashboards.</p><div class="actions"><a class="button" href="#case">Explore the case study ↓</a><a class="button light" href="${github}" target="_blank" rel="noreferrer">Open repository ↗</a></div></div><aside class="hero-side"><strong>2021–25</strong><p>Ten half-year reporting periods, reconciled into one analysis-ready model with source-cell lineage.</p></aside></div></section>
<section class="metrics"><div class="shell metrics-grid"><div class="metric"><strong>75,231</strong><span>source metric records</span></div><div class="metric"><strong>5,751</strong><span>firm-product-period observations</span></div><div class="metric"><strong>10</strong><span>half-year reporting periods</span></div><div class="metric"><strong>85</strong><span>automated tests</span></div></div></section>
<section class="section shell" id="case"><div class="section-head"><div><div class="kicker">The challenge</div><h2>Structure first. Analysis second.</h2></div><p>The FCA workbooks changed across periods, mixed multiple metric types, used special missing markers and embedded business meaning in formatting. The solution preserves every raw file, discovers layouts programmatically and records every transformation.</p></div><div class="workflow">${[
  ["01","Profile","Discover workbook structures, sheets, headers and schema drift."],
  ["02","Extract","Standardise period-specific Excel layouts without changing raw files."],
  ["03","Validate","Reconcile totals, preserve lineage and surface quality exceptions."],
  ["04","Analyse","Build peer benchmarks, transparent signals and review queues."],
  ["05","Explain","Connect every dashboard result to its rule and source cell."]
].map(x=>`<article class="step"><b>${x[0]}</b><h3>${x[1]}</h3><p>${x[2]}</p></article>`).join("")}</div></section>
<section class="section findings" id="findings"><div class="shell"><div class="section-head"><div><div class="kicker">Selected findings</div><h2>A focused queue—not an automated verdict.</h2></div><p>The warning framework separates signals, insufficient evidence and confirmed source anomalies. Results support human prioritisation and are explicitly not findings of misconduct or customer harm.</p></div><div class="finding-grid"><article class="finding"><strong>13</strong><h3>Latest priority observations</h3><p>A focused investigation queue across 13 firms in 2025-H2.</p></article><article class="finding"><strong>71</strong><h3>Insufficient-evidence observations</h3><p>Kept separate from no-current-signal results to avoid false reassurance.</p></article><article class="finding"><strong>1</strong><h3>Confirmed source anomaly</h3><p>Preserved exactly as published and excluded from misleading derivations.</p></article></div></div></section>
<section class="section shell"><div class="section-head"><div><div class="kicker">Decision layer</div><h2>Signals that can be traced and challenged.</h2></div><p>Peer position, trend deterioration, persistence and data sufficiency are visible together. Reviewers can move from a portfolio signal to its rule definition and original workbook cell.</p></div><div class="dashboard"><div class="dash-top"><strong>Executive overview · 2025-H2</strong><div class="lights"><i></i><i></i><i></i></div></div><div class="dash-grid"><div class="panel"><h4>Warning trend</h4><div class="bars">${[38,52,49,61,55,67,59,73,65,78].map(h=>`<span class="bar" style="height:${h}%"></span>`).join("")}</div></div><div class="panel"><h4>Latest product signals</h4><div class="signals">${[["Insurance & protection",92],["Consumer credit",70],["Investments",52],["Home finance",39],["Banking & cards",34]].map(x=>`<div class="signal"><div><small>${x[0]}</small><div class="track"><div class="fill" style="width:${x[1]}%"></div></div></div><b>${x[1]}</b></div>`).join("")}</div></div></div></div></section>
<section class="section shell" id="method"><div class="section-head"><div><div class="kicker">Tools and judgement</div><h2>Built like a production analytics project.</h2></div><p>Reusable Python modules, governed mappings, automated validation and documented analytical limitations make the work reproducible—not merely presentable.</p></div><div class="skills">${["Python","pandas","openpyxl","pytest","Tableau","Data profiling","Data modelling","Quality assurance","Risk analytics","Governance"].map(x=>`<span class="chip">${x}</span>`).join("")}</div><div class="lesson-grid"><div class="lesson"><b>01</b><h3>Respect source meaning</h3><p>Percentages, rates and counts remain distinct even when labels appear similar.</p></div><div class="lesson"><b>02</b><h3>Make uncertainty visible</h3><p>Missing evidence is not translated into low risk or a zero.</p></div><div class="lesson"><b>03</b><h3>Keep humans accountable</h3><p>Rules prioritise review; documented judgement determines action.</p></div></div></section>
</main><footer><div class="shell footer-grid"><div><h2>Explore the complete project.</h2><p>Read the methodology, tests, governance documentation and reusable source code on GitHub.</p></div><div class="foot-links"><a class="button light" href="${github}" target="_blank" rel="noreferrer">View repository ↗</a></div></div></footer>
</body></html>`;

export default {
  async fetch(request) {
    const url = new URL(request.url);
    if (url.pathname === "/health") {
      return new Response("ok", { headers: { "content-type": "text/plain" } });
    }
    return new Response(html, {
      headers: {
        "content-type": "text/html; charset=utf-8",
        "cache-control": "public, max-age=300",
        "x-content-type-options": "nosniff",
        "referrer-policy": "strict-origin-when-cross-origin",
      },
    });
  },
};
